export const FETCH_GIRAFFES = 'FETCH_GIRAFFES'
export const ADD_GIRAFFE = 'ADD_GIRAFFE'
export const REMOVE_GIRAFFE = 'REMOVE_GIRAFFE'
export const EDIT_GIRAFFE = 'EDIT_GIRAFFE'

export const SHOW_MANAGE_WINDOW = 'SHOW_MANAGE_WINDOW'
export const HIDE_MANAGE_WINDOW = 'HIDE_MANAGE_WINDOW'